# Generated by Django 6.1.1 on 2026-10-08 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('guisos', 'Guisos y Ollas'), ('carnes', 'Carnes y Parrilla'), ('pastas', 'Pastas con Tuco'), ('clasicos', 'Clásicos de Bodegón')], default='clasicos', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: El guiso que hacía mi abuela los domingos', max_length=250)),
                ('ingredientes', models.TextField(help_text='Uno por línea')),
                ('pasos', models.TextField()),
                ('tiempo', models.CharField(default='60 min', max_length=50)),
                ('dificultad', models.CharField(default='Media', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
